# Generated by Django 3.2.6 on 2021-10-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211009_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
